include_guard = "DHC_H"
include_version = true

line_length = 100
tab_width = 2
language = "C++"
documentation_style = "C++"

[parse]
parse_deps = false

[export]
item_types = ["globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]
